changed workflow

diff --git a/.github/workflows/tester.yml b/.github/workflows/tester.yml
--- a/.github/workflows/tester.yml
+++ b/.github/workflows/tester.yml
@@ -104,12 +104,12 @@ jobs:
           
           if [ "${{ steps.package.outputs.name }}" != "jobmetric/laravel-package-tester" ]; then
             composer config --json --no-interaction repositories.tester_package "{\"type\":\"vcs\",\"url\":\"https://github.com/jobmetric/laravel-package-tester.git\"}"
-            composer require --dev --no-interaction --no-progress -W "$TESTER_PACKAGE" || echo "Warning: Could not install tester package, continuing..."
+            composer require --dev --no-interaction --no-progress --no-update "$TESTER_PACKAGE" || echo "Warning: Could not add tester package, continuing..."
           fi
 
-          composer require --dev --no-interaction --no-progress -W "${{ steps.package.outputs.name }}:${TARGET_PACKAGE_VERSION}"
+          composer require --dev --no-interaction --no-progress --no-update "${{ steps.package.outputs.name }}:${TARGET_PACKAGE_VERSION}"
 
-          composer install --no-interaction --no-progress --prefer-dist
+          composer update --no-interaction --no-progress --prefer-dist --with-all-dependencies
           composer dump-autoload --no-interaction --no-progress -o
 
       - name: Prepare Laravel application
